# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             5000
encoding:         UTF-8

# Custom vars
current_version:  0.0.1
base_url:         advcal
repo:             https://github.com/aanoaa/advcal

cdn:
  jquery:         https://code.jquery.com/jquery-2.1.4.min.js
  bootstrap_js:   https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js
  bootstrap_css:  https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css
  anchor:         https://cdnjs.cloudflare.com/ajax/libs/anchor-js/2.0.0/anchor.min.js
  font_awesome:   http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css
